setwd("/Users/bruno/Projects/Coursera/Exploratory Data Analysis/ExData_Plotting1/")
household_power_consumption<-read.csv(file="exdata-data-household_power_consumption/household_power_consumption.txt",sep=";")
new_household_power_consumption<-subset(household_power_consumption,as.Date(Date,"%d/%m/%Y")>=as.Date("2007-02-01") & as.Date(Date,"%d/%m/%Y")<=as.Date("2007-02-02"))
png('plot3.png',width=480,height=480)
with(new_household_power_consumption,plot(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),as.numeric(Sub_metering_1),type="n",xlab="",ylab="Energy sub metering"))
with(new_household_power_consumption,lines(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),as.numeric(Sub_metering_1),type="l",col="black"))
with(new_household_power_consumption,lines(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),as.numeric(Sub_metering_2),type="l",col="red"))
with(new_household_power_consumption,lines(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),as.numeric(Sub_metering_3),type="l",col="blue"))
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1),cex=0.7)
dev.off()